### ISSUE TITLE
Don't display venn chart when running npm build. 

### ISSUE THREAD

**Issue by sam61086** [A2ayak/vue3-venn-chart#1]
In the development environment, the Venn diagram can be displayed, but once it is built (npm run build), it cannot be displayed, and the console message is "请检查是否存在图表容器dom节点,并设置好宽高".
Project is built by vuetify 3.4

**Comment by A2ayak** [comment]
@sam61086  Any online demo？It means "Please check if the chart container dom exists, and make sure the width and height are set."

**Comment by A2ayak** [comment]
@sam61086 Fix it in version 1.0.7, thanks for the issue.
